### ISSUE TITLE
User-facing links should point to ui.adsabs instead of api.adsabs

### ISSUE THREAD

**Issue by episanty** [mattbierbaum/arxiv-bib-overlay#4]
The current version produces user-facing links which point to api.adsabs.harvard.edu, and those should link instead to ui.adsabs.harvard.edu. From an email by the ADS support staff:

> For future reference, ui.adsabs.harvard.edu is our standard URL for access via a web browser, while the api.adsabs.harvard.edu is the standard URL for making API queries from the command line or Python.

This is mostly a minor issue, but it can indeed cause problems. In particular, (at least, as of yesterday), the following fails:

 - open an arXiv abstract page with the extension open
 - click on the link with the paper title on the right-hand sidebar, going to api.adsabs.harvard.edu
 - create a new account
 - attempt to link this new account to an existing ORCID account.

This produces an error from ORCID saying "redirect URI doesn't match your registered redirect URIs", and the ADS support staff have confirmed that this is because the call was made from the api.* domain. 

Instead of forcing ADS to try to figure out which clients to redirect to ui.*, why not link directly there from the extension?

**Comment by mattbierbaum** [comment]
Thank you for looking into this, that does make sense. It is fixed on 4ee430f and cb871e1 and will be rolled out soon.
